name: Accessibility Check

on:
  push:
    branches:
    - main

#le build doit tourner sur la dernière version d'ubuntu
jobs:
  check-accessibility:
    runs-on: ubuntu-latest
    steps:
      # je charge les fichiers du projet
      - name: Checkout code
        uses: actions/checkout@v4
      # je définie la version du Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      # J'installe les dépendances npm
      - name: Install Dependencies
        run: npm install
      # Je lance le fichier index.js et attend 5 secondes qu'il démarre
      - name: Start Node server
        run: node index.js & sleep 5 
      # J'installe la dépendance pa11y 
      - name: Install Pa11y
        run: npm install -g pa11y-ci
      # Je lui demande de scanner le code dispo à l'url présente dans le fichier pa11-ci.json
      - name: Run accessibility tests
        run: pa11y-ci --config pa11y-ci.json
